# Generated by Django 2.2.4 on 2020-07-01 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='DataStorage/Images/% Y/% m/% d/')),
                ('file', models.FileField(upload_to='DataStorage/FileStore/% Y/% m/% d/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
        ),
    ]
