# Generated by Django 2.2.4 on 2020-07-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_studentdata_useredit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='file',
        ),
        migrations.AddField(
            model_name='student',
            name='phy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/% Y/% m/% d/'),
        ),
    ]
