# Generated by Django 2.2.4 on 2020-07-01 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200701_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='student',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
    ]
