# Generated by Django 2.2.4 on 2020-07-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200701_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
    ]
