# Generated by Django 2.2.4 on 2020-07-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200702_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/% Y/% m/% d/'),
        ),
    ]
