# Generated by Django 2.2.4 on 2020-07-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200702_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='doc',
            field=models.FileField(default='ss', upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
